version: '3'
services:
  python3:
    container_name: 'python3'
    build: ./ENB/python
    restart: always
    entrypoint: >
      jupyter-lab
      --ip=0.0.0.0
      --port=8888
      --NotebookApp.token=''
      --notebook-dir=/home/user/src
    ports:
      - "127.0.0.1:8888:8888"
    working_dir: '/home/user/src'
    tty: true
    volumes:
      - ./src:/home/user/src
